### ISSUE TITLE
[BE] DB 설계

### ISSUE THREAD

**Issue by haveagood** [codesquad-member-2020/baseball-08#4]
- [x] DB 구조 논의
- [x] ERD 작성
- [x] 게임 데이터를 저장하는 DB
- [x] 팀 정보 데이터를 저장하는 DB
- [x] 선수별 게임 로그 DB - 추후 변경 예정

**Comment by haveagood** [comment]
<img width="1239" alt="스크린샷 2020-05-05 오후 4 04 00" src="https://user-images.githubusercontent.com/42365037/81041988-1db34200-8eea-11ea-9d45-1fbec3e98c98.png">

**Comment by wooody92** [comment]
<img width="1043" alt="스크린샷 2020-05-14 오전 12 28 43" src="https://user-images.githubusercontent.com/58318041/81833017-27881580-957a-11ea-94c8-fd941a97b44e.png">
